/** A preset Fish Audio voice the user can choose on the landing page. */
export interface PresetVoice {
  id: string;
  name: string;
  /** Short accent/gender descriptor, e.g. "American · Male". */
  descriptor: string;
  /** Static preview clip under /public, generated by fish/scripts/gen_voice_samples.py. */
  sampleUrl: string;
}

// Keep in sync with PRESET_VOICES in fish/src/agent.py.
export const PRESET_VOICES: PresetVoice[] = [
  {
    id: '0e24ff9936d34df4bddce26398cf1311',
    name: 'Maren',
    descriptor: 'American · Female',
    sampleUrl: '/voice-samples/0e24ff9936d34df4bddce26398cf1311.mp3',
  },
  {
    id: '747b05c0add940baa95270cf68c0cc2e',
    name: 'Stellan',
    descriptor: 'American · Male',
    sampleUrl: '/voice-samples/747b05c0add940baa95270cf68c0cc2e.mp3',
  },
  {
    id: '41db1fc3c3624332bec9997ff3d3d353',
    name: 'Maeve',
    descriptor: 'British · Female',
    sampleUrl: '/voice-samples/41db1fc3c3624332bec9997ff3d3d353.mp3',
  },
  {
    id: '9a3a69c63dbc4774ac41b03945229dc8',
    name: 'Alistair',
    descriptor: 'British · Male',
    sampleUrl: '/voice-samples/9a3a69c63dbc4774ac41b03945229dc8.mp3',
  },
];

/** Sentinel selection value meaning "clone my own voice" rather than a preset id. */
export const CLONE_SELECTION = 'clone' as const;

/** Sentinel selection value meaning "design a voice from a text description". */
export const DESIGN_SELECTION = 'design' as const;

/** Max characters accepted for a voice-design description (Fish's API caps it at 2000). */
export const DESIGN_INSTRUCTION_MAX_CHARS = 2000;

/** Default landing-page selection — the first preset (Maren, American female). */
export const DEFAULT_VOICE_ID = PRESET_VOICES[0].id;

export interface AppConfig {
  pageTitle: string;
  pageDescription: string;
  companyName: string;

  supportsVideoInput: boolean;
  supportsScreenShare: boolean;
  isPreConnectBufferEnabled: boolean;

  startButtonText: string;
  accent?: string;
  accentDark?: string;

  // agent dispatch configuration
  agentName?: string;

  // LiveKit Cloud Sandbox configuration
  sandboxId?: string;
}

export const APP_CONFIG_DEFAULTS: AppConfig = {
  companyName: 'Fish Audio',
  pageTitle: 'Talk to an expressive voice agent — powered by Fish Audio',
  pageDescription:
    "Talk to a voice agent running Fish Audio's expressive TTS. Flip it between casual and professional mid-call and watch its mood shift in real time. You can also clone your own voice from a short scripted read; your recording and the clone are deleted when the call ends.",

  supportsVideoInput: false,
  supportsScreenShare: false,
  isPreConnectBufferEnabled: false,

  accent: '#002cf2',
  accentDark: '#1fd5f9',
  startButtonText: 'Start call',

  // agent dispatch configuration — NAMED dispatch so per-session config (chosen
  // voice / clone flag) rides agentMetadata to the worker. Must match AGENT_NAME
  // in fish/src/agent.py. Hardcoded (not env-gated) so a missing env var can't
  // silently fall back to auto-dispatch and break the metadata channel.
  agentName: process.env.AGENT_NAME ?? 'fish-demo',

  // LiveKit Cloud Sandbox configuration
  sandboxId: undefined,
};
