import type { Locale } from '@/lib/i18n';

/** A preset Fish Audio voice the user can choose on the landing page. */
export interface PresetVoice {
  id: string;
  name: string;
  /** Short accent/gender descriptor, e.g. "American · Male". */
  descriptor: string;
  /** Static preview clip under /public, generated by fish/scripts/gen_voice_samples.py. */
  sampleUrl: string;
}

// Keep in sync with PRESET_VOICES["en"] in fish/src/agent.py.
export const PRESET_VOICES: PresetVoice[] = [
  {
    id: '0e24ff9936d34df4bddce26398cf1311',
    name: 'Maren',
    descriptor: 'American · Female',
    sampleUrl: '/voice-samples/0e24ff9936d34df4bddce26398cf1311.mp3',
  },
  {
    id: '747b05c0add940baa95270cf68c0cc2e',
    name: 'Stellan',
    descriptor: 'American · Male',
    sampleUrl: '/voice-samples/747b05c0add940baa95270cf68c0cc2e.mp3',
  },
  {
    id: '41db1fc3c3624332bec9997ff3d3d353',
    name: 'Maeve',
    descriptor: 'British · Female',
    sampleUrl: '/voice-samples/41db1fc3c3624332bec9997ff3d3d353.mp3',
  },
  {
    id: '9a3a69c63dbc4774ac41b03945229dc8',
    name: 'Alistair',
    descriptor: 'British · Male',
    sampleUrl: '/voice-samples/9a3a69c63dbc4774ac41b03945229dc8.mp3',
  },
];

// Japanese presets for the /jp page. Keep in sync with PRESET_VOICES["ja"] in
// fish/src/agent.py.
export const PRESET_VOICES_JA: PresetVoice[] = [
  {
    id: '297a6fd278df47c3b9da9bfdf55ac89a',
    name: 'さとる',
    descriptor: '男性 · 落ち着いたナレーション',
    sampleUrl: '/voice-samples/297a6fd278df47c3b9da9bfdf55ac89a.mp3',
  },
  {
    id: '88ee033403f24744965262d7369686e1',
    name: 'まり',
    descriptor: '女性 · やわらかく穏やか',
    sampleUrl: '/voice-samples/88ee033403f24744965262d7369686e1.mp3',
  },
  {
    id: '8d7ac3b4f8cc4f7cbe2f39887e8c5247',
    name: '丁寧な青年',
    descriptor: '男性 · 誠実で丁寧',
    sampleUrl: '/voice-samples/8d7ac3b4f8cc4f7cbe2f39887e8c5247.mp3',
  },
  {
    id: 'b2d9d8db057042688a5e318b8f405bc2',
    name: 'きょうこ',
    descriptor: '女性 · カスタマーサポート',
    sampleUrl: '/voice-samples/b2d9d8db057042688a5e318b8f405bc2.mp3',
  },
];

/** The preset list shown on a given locale's landing page. */
export function getPresetVoices(locale: Locale): PresetVoice[] {
  return locale === 'ja' ? PRESET_VOICES_JA : PRESET_VOICES;
}

/** Default landing-page selection for a locale — its first preset. */
export function getDefaultVoiceId(locale: Locale): string {
  return getPresetVoices(locale)[0].id;
}

/** Sentinel selection value meaning "clone my own voice" rather than a preset id. */
export const CLONE_SELECTION = 'clone' as const;

/** Sentinel selection value meaning "design a voice from a text description". */
export const DESIGN_SELECTION = 'design' as const;

/**
 * Sentinel selection value for the /chat-to-clone conversational-cloning page: no
 * scripted read — just talk for ~10s and the agent clones you mid-conversation.
 * Rides the agent metadata as `{"chatClone": true}`.
 */
export const CHAT_CLONE_SELECTION = 'chat-clone' as const;

/** Max characters accepted for a voice-design description (Fish's API caps it at 2000). */
export const DESIGN_INSTRUCTION_MAX_CHARS = 2000;

/** Default landing-page selection — the first preset (Maren, American female). */
export const DEFAULT_VOICE_ID = PRESET_VOICES[0].id;

export interface AppConfig {
  pageTitle: string;
  pageDescription: string;
  companyName: string;

  supportsVideoInput: boolean;
  supportsScreenShare: boolean;
  isPreConnectBufferEnabled: boolean;

  startButtonText: string;
  accent?: string;
  accentDark?: string;

  // agent dispatch configuration
  agentName?: string;

  // LiveKit Cloud Sandbox configuration
  sandboxId?: string;
}

export const APP_CONFIG_DEFAULTS: AppConfig = {
  companyName: 'Fish Audio',
  pageTitle: 'Talk to an expressive voice agent — powered by Fish Audio',
  pageDescription:
    "Talk to a voice agent running Fish Audio's expressive TTS. Flip it between casual and professional mid-call and watch its mood shift in real time. You can also clone your own voice from a short scripted read; your recording and the clone are deleted when the call ends.",

  supportsVideoInput: false,
  supportsScreenShare: false,
  isPreConnectBufferEnabled: false,

  accent: '#002cf2',
  accentDark: '#1fd5f9',
  startButtonText: 'Start call',

  // agent dispatch configuration — NAMED dispatch so per-session config (chosen
  // voice / clone flag) rides agentMetadata to the worker. Must match AGENT_NAME
  // in fish/src/agent.py. Hardcoded (not env-gated) so a missing env var can't
  // silently fall back to auto-dispatch and break the metadata channel.
  agentName: process.env.AGENT_NAME ?? 'fish-demo',

  // LiveKit Cloud Sandbox configuration
  sandboxId: undefined,
};

// Japanese page copy for /jp. Everything else (agent name, accents, flags) is
// shared with the defaults above.
const JA_PAGE_TEXT: Pick<AppConfig, 'pageTitle' | 'pageDescription' | 'startButtonText'> = {
  pageTitle: '表現力豊かなボイスエージェントと話そう — Fish Audio',
  pageDescription:
    'Fish Audioの表現力豊かな音声合成で動くボイスエージェントと話せます。通話中にカジュアルとフォーマルを切り替えると、ムードがリアルタイムに変わります。短いスクリプトを読んで自分の声をクローンすることも可能です。録音とクローンは通話終了時に削除されます。',
  startButtonText: '通話を開始',
};

/** Overlay the locale's page copy onto a base config ('en' passes through). */
export function localizeAppConfig(config: AppConfig, locale: Locale): AppConfig {
  return locale === 'ja' ? { ...config, ...JA_PAGE_TEXT } : config;
}
